Adding Hip spaces ... already without `Experimental`
kokkos/kokkos-core-wiki pull request #126
Opened 2022-07-29 01:00 UTC by JBludau

It contains only a minimal hint on the `xnack` rabbithole

2022-07-29 02:30 UTC, dalg24 requested changes
Add the `Experimental::`.  We will need to add some language about when the promotion to the `Kokkos::` namespace happened.

2022-07-29 04:49 UTC, JBludau commented
how about this?
<img width="750" alt="image" src="https://user-images.githubusercontent.com/104908666/181684913-205b8e43-658d-43aa-a25e-463c5c7a3158.png">

2022-07-29 12:05 UTC, dalg24 approved these changes

2022-08-01 09:37 UTC, Rombur approved these changes

2022-08-01 13:00 UTC, merged