#120: API-containers-Bitset from md to rst
kokkos/kokkos-core-wiki pull request #150
Opened 2022-08-30 14:48 UTC by marcinwrobel1986

### THIS PR:
- API/containers/Bitset transition from .md to .rst

Below render of the API/containers/Bitset after transition:
![Zrzut ekranu z 2022-08-30 16-42-59](https://user-images.githubusercontent.com/47597569/187467895-e805a298-c295-465f-848d-c36b1726cff7.png)
![Zrzut ekranu z 2022-08-30 16-43-16](https://user-images.githubusercontent.com/47597569/187467921-bd8cce1d-0c17-43fa-aa1c-86bb599e125d.png)
![Zrzut ekranu z 2022-08-30 16-43-31](https://user-images.githubusercontent.com/47597569/187467969-f905af46-93a2-4133-8537-09e87c5d7bb3.png)

![Zrzut ekranu z 2022-08-30 16-46-36](https://user-images.githubusercontent.com/47597569/187468280-3d1c2312-612d-4402-a5cf-bbc710752467.png)
![Zrzut ekranu z 2022-08-30 16-46-57](https://user-images.githubusercontent.com/47597569/187468335-8f399067-1a33-4390-8e4e-ea69f7c5b04d.png)
![Zrzut ekranu z 2022-08-30 16-47-11](https://user-images.githubusercontent.com/47597569/187468360-a56c03e3-8a4c-4545-ab30-6fa12ac03ce3.png)

2022-08-31 06:34 UTC, fnrizzi commented
@marcinwrobel1986 is this just the new render with dark/light mode? where is the old one?

2022-08-31 16:49 UTC, marcinwrobel1986 commented
> @marcinwrobel1986 is this just the new render with dark/light mode? where is the old one?

The old one is [HERE](https://kokkos.github.io/kokkos-core-wiki/API/containers/Bitset.html)

2022-09-01 17:56 UTC, crtrott requested changes
Just remove that ConstBitset thing further up then its good.

2022-09-01 17:56 UTC, crtrott commented on docs/source/API/containers/Bitset.rst
> +
Remove the ConstBitset here.

2022-09-02 09:22 UTC, fnrizzi commented on docs/source/API/containers/Bitset.rst
> +
done

2022-09-02 09:22 UTC, merged