single.md: responding to issue #5459
kokkos/kokkos-core-wiki pull request #178
Opened 2022-10-03 18:17 UTC by ajpowelsnl

This PR represents a first draft of the `Kokkos::single` API documentation.  We placed it under `parallel_dispatch` because it is used within parallel regions.

2022-10-17 16:36 UTC, JBludau requested changes
I think it is more of in a draft state. Also needs to be added into the toc and alphabetical

2022-10-17 16:36 UTC, JBludau commented on docs/source/API/core/parallel-dispatch/single.md
> +
why is there a `fence()` call here?

2022-10-17 16:36 UTC, JBludau commented on docs/source/API/core/parallel-dispatch/single.md
> +
If it was intended to be the title it should also contain a label so other pages can reference it.

2022-10-17 16:36 UTC, JBludau commented on docs/source/API/core/parallel-dispatch/single.md
> +```
I think the c++ block in this section should contain a 1-2 line call that conveys how it is used.

2022-10-17 16:36 UTC, JBludau commented on docs/source/API/core/parallel-dispatch/single.md
> +The `single` function can take two arguments:  an execution `Policy` and a `Lambda`.  `Kokkos::single` is only valid for the `Lambda` to capture variables by value (i.e., [=], and not [&]). That `Lam
```suggestion
The `single` function can take two arguments:  an execution `Policy` and a `Lambda`.  `Kokkos::single` is only valid if the `Lambda` captures variables by value (i.e., [=], and not [&]). The `Lambda` can take zero or one arguments by reference.  If it takes one argument, the final value of that argument is broadcast to every executor, for example, every vector lane of the Thread, or every Thread (and vector lane) of the Team. 
```

2022-10-17 16:36 UTC, JBludau commented on docs/source/API/core/parallel-dispatch/single.md
> +- `Policy`: Defines how the execution will be performed (in the context of a parallel dispatch statement)..
I would either remove the list of one item or add the second argument and an explanation for it, even though it might seem obvious.

2022-10-17 16:36 UTC, JBludau commented on docs/source/API/core/parallel-dispatch/single.md
> +- `Policy`: Defines how the execution will be performed (in the context of a parallel dispatch statement)..
```suggestion
- `Policy`: Defines how the execution will be performed (in the context of a parallel dispatch statement).
```

2022-10-17 16:36 UTC, JBludau commented on docs/source/API/core/parallel-dispatch/single.md
> +
The requirements are in the description. I think it would make sense to consolidate it somehow.

2022-10-17 16:36 UTC, JBludau commented on docs/source/API/core/parallel-dispatch/single.md
> +- Focuses execution in parallel regions to a single work item for the `Policy`.
I would delete this section

2022-10-17 16:36 UTC, JBludau commented on docs/source/API/core/parallel-dispatch/single.md
> +TeamPolicy<...> policy (...);
could you make the example compilable?

2022-10-17 16:36 UTC, JBludau commented on docs/source/API/core/parallel-dispatch/single.md
> +typedef TeamPolicy<...>::member_type team_member;
I would not mix using and typedef

2022-10-17 16:36 UTC, JBludau commented on docs/source/API/core/parallel-dispatch/single.md
> +using Kokkos::PerThread;
I think we should get rid of these here and use the namespace in the call as we do for `Single` in the example.

2024-01-09 20:49 UTC, ajpowelsnl commented
Info not used

2024-01-09 20:49 UTC, closed without merging