#120: API containers Offset-View transition
kokkos/kokkos-core-wiki pull request #198
Opened 2022-10-27 14:43 UTC by marcinwrobel1986

### THIS PR:
- convert Offset-View from md to rst
### TODO:
- use cppkokkos domain instead of cpp
- probably experimental space should have been used

2023-02-20 08:57 UTC, fnrizzi approved these changes

2023-03-02 20:44 UTC, Rombur requested changes

2023-03-02 20:44 UTC, Rombur commented on docs/source/API/containers/Offset-View.rst
> +returns a value that is not a legal index:  It is exactly one more than the maximum allowable index for the given dimenion i.
```suggestion
returns a value that is not a legal index:  It is exactly one more than the maximum allowable index for the given dimension i.
```

2023-03-03 16:28 UTC, fnrizzi approved these changes

2023-03-03 16:29 UTC, Rombur approved these changes

2023-03-03 16:30 UTC, merged