#120: API-core-policies-TeamThreadRange from md to rst
kokkos/kokkos-core-wiki pull request #245
Opened 2022-12-29 15:27 UTC by antoinemeyer5

### THIS PR:
* API/core/policies/TeamThreadRange transition from .md to .rst

before (.md) | after (.rst)
:----------------: | :-------------: 
![before_1](https://user-images.githubusercontent.com/62652182/209974463-58f61fe5-4505-48e7-b5b7-8447dfb72c01.png) | ![after_1](https://user-images.githubusercontent.com/62652182/209974462-64d17560-2282-468e-b2d8-aac3a67b85cf.png)
![before_2](https://user-images.githubusercontent.com/62652182/209974459-8989777c-9708-4de4-b15e-8db35ceabbf1.png) | ![after_2](https://user-images.githubusercontent.com/62652182/209974458-155878fd-370c-405b-8585-a5dcae0f45a6.png)
![before_3](https://user-images.githubusercontent.com/62652182/209974457-e2472c14-6286-441d-85e9-4dcd94ea9a62.png) | ![after_3](https://user-images.githubusercontent.com/62652182/209974455-1feedacc-4a00-4d43-91e7-cda749d71f9e.png)

2023-01-02 14:52 UTC, fnrizzi commented on docs/source/API/core/policies/TeamThreadRange.rst
> +    - ``count >= 0`` is true;
all of the above should be indented so that it is under the corresponding constructor

2023-01-02 14:53 UTC, fnrizzi commented on docs/source/API/core/policies/TeamThreadRange.rst
> +    - ``end >= begin`` is true;
similar comment as above

2023-01-03 16:10 UTC, antoinemeyer5 commented
indentation corrected, screenshots are up to date ! @fnrizzi & @ajpowelsnl

2023-01-06 12:04 UTC, fnrizzi approved these changes

2023-01-06 12:05 UTC, fnrizzi commented on docs/source/API/core/policies/TeamThreadRange.rst
> +    .. /* Implementation defined */
we cannot comment this out even if it is in the synopsis

2023-01-06 12:06 UTC, fnrizzi commented on docs/source/API/core/policies/TeamThreadRange.rst
> +    .. /* Implementation defined */
same comment as above

2023-01-06 12:06 UTC, fnrizzi requested changes
see my comments

2023-01-16 20:32 UTC, ajpowelsnl approved these changes
Looks good!

2023-01-25 10:06 UTC, fnrizzi approved these changes

2023-01-25 10:07 UTC, merged