#251: add customization `kokkosinlinefunction` to sphinx
kokkos/kokkos-core-wiki pull request #256
Opened 2023-01-12 11:26 UTC by antoinemeyer5

This PR adds the following customization to cppkokkos to automatically add markup `KOKKOS_INLINE_FUNCTION`:

# CODE example 

```
``Title``
=========

.. role::cpp(code)
    :language: cpp

.. role:: cppkokkos(code)
    :language: cppkokkos

Section
-------

.. cpp:class:: MyCoolClass

    .. cpp:function:: void nonTemplatedFunc(double d) ;

    .. cppkokkos:kokkosinlinefunction:: nonTemplatedFunc(double arg) ;

    .. cpp:function:: template<class T> void templatedFunc(const T& arg) ;

    .. cppkokkos:kokkosinlinefunction:: template<class T> void templatedFunc(const T & arg) ;
```

# Result

![image](https://user-images.githubusercontent.com/18708772/212033756-8e94c1f2-e1e4-4d69-a932-9684c18336e6.png)

2023-01-12 11:51 UTC, fnrizzi commented on docs/source/_ext/cppkokkos.py
> +                 assert False
@antoinemeyer5 can you please fix this indentation? I think it is my fault but can you please make indentation to be 4 characters?

2023-01-12 11:51 UTC, fnrizzi commented on docs/source/_ext/cppkokkos.py
> +                 assert False
those weird green things make me think the indentation is set to 5

2023-01-12 11:52 UTC, fnrizzi requested changes
see my comment about indentation

2023-01-12 13:57 UTC, fnrizzi approved these changes

2023-01-16 09:52 UTC, JBludau approved these changes
looks good

2023-01-16 10:51 UTC, cz4rs approved these changes

2023-01-16 10:57 UTC, fnrizzi commented
the name was suggested/approved during team meeting on Jan 11 2023 (see internal notes)

2023-01-16 10:57 UTC, merged