#120: API-core-builtinreducers-Prod transition from md to rst
kokkos/kokkos-core-wiki pull request #270
Opened 2023-01-21 15:33 UTC by antoinemeyer5

### THIS PR:
* API/core/builtinreducers/Prod transition from .md to .rst

before (.md) | after (.rst)
:----------------: | :-------------:
![before1](https://user-images.githubusercontent.com/62652182/213874188-eb22d495-9224-4889-92bc-9580a7b95336.png) | ![after1](https://user-images.githubusercontent.com/62652182/213874180-9b48b1bb-4ac9-4e4f-882a-6d05828cb493.png)
![before2](https://user-images.githubusercontent.com/62652182/213874183-e5e03fb1-8527-4bdd-a9f7-66e17c9e800d.png) | ![after2](https://user-images.githubusercontent.com/62652182/213874178-0d8c4d27-ed36-4ae8-aa42-505f0e26e371.png)
![before3](https://user-images.githubusercontent.com/62652182/213874182-a615badf-12f6-49de-97fd-5965c79da8d6.png) | ![after3](https://user-images.githubusercontent.com/62652182/213874177-9677798f-3049-4b0e-9693-af03de13c363.png)

2023-01-23 17:10 UTC, fnrizzi requested changes
see my comment on indentation here: https://github.com/kokkos/kokkos-core-wiki/pull/271/files#r1084323761

2023-01-23 18:30 UTC, nmm0 requested changes

2023-01-23 18:30 UTC, nmm0 commented on docs/source/API/core/builtinreducers/Prod.rst
> +* Initialize ``val`` using the Kokkos::reduction_identity<Scalar>::prod() method. The default implementation sets ``val=1``.
Please make `Kokkos::reduction_identity` a cross-reference to the class or at least monospace

2023-01-25 00:18 UTC, nmm0 approved these changes
:+1:

2023-01-25 09:53 UTC, fnrizzi approved these changes

2023-01-25 09:53 UTC, merged