`TeamThreadMDRange` to rst
kokkos/kokkos-core-wiki pull request #395
Opened 2023-06-07 06:46 UTC by fnrizzi

2023-06-12 23:45 UTC, ajpowelsnl commented
@fnrizzi -- in an effort to move towards a standard for API entries we decided on these main sections:

- Name
- Header file
- Description
- Interface
- Parameters
- Constructors (where relevant)
- Methods
- Example

Nic's PR summarizes this standard:

[TEMPLATE FOR API ENTRY](https://github.com/kokkos/kokkos-core-wiki/pull/385/files)

Would it be possible to re-work this PR for the new standard?

2023-06-13 00:08 UTC, ajpowelsnl requested changes

2023-06-13 00:08 UTC, ajpowelsnl commented on docs/source/API/core/policies/TeamVectorMDRange.rst
> +
Move general form from above to the beginning of the Example as a comment.

2023-06-13 00:08 UTC, ajpowelsnl commented on docs/source/API/core/policies/ThreadVectorMDRange.rst
> +
Please change `Usage` to `Description` and add a couple of explanatory sentences.

2023-06-13 00:08 UTC, ajpowelsnl commented on docs/source/API/core/policies/ThreadVectorMDRange.rst
> -  ```
Move the general form to the beginning of the Example as a comment.

2023-06-13 00:08 UTC, ajpowelsnl commented on docs/source/API/core/policies/ThreadVectorMDRange.rst
> -## Description
Are lines 33 -34 an overview of what `ThreadVectorMDRange` does?  If so please see comment above about `Usage`.  Following the recently-adopted standard for API entries, `Arguments` would become `Parameters`, and `Requirements` would be expressed as required parameters (vs. optional).

2023-06-13 23:20 UTC, ldh4 approved these changes

2023-06-29 12:48 UTC, masterleinad approved these changes
Looks OK to me.

2023-06-29 15:40 UTC, crtrott approved these changes

2023-06-29 15:40 UTC, merged