Documentation/revise view
kokkos/kokkos-core-wiki pull request #455
Opened 2023-09-06 17:36 UTC by ajpowelsnl

Minor edits to View to stage for conversion to new API standard entry.

2023-11-20 22:00 UTC, crtrott requested changes
This can't be merged there are a whole bunch of mistakes in this which need fixing.

2023-11-20 22:00 UTC, crtrott commented on docs/source/API/core/view/view.rst
> +The programming model's main data structure is the Kokkos View.  The View has multi-dimensional (up to eight) array-like semantics and operations.  It, and related data structures (*e.g.*, `View-like
This is mostly not quite right. View does not have array-like semantics or operations actually. It also doesn't have shared-memory parallelism per-se, and I wouldn't necessarily call it the programming model's main data structure - which has some unfortunate connotations.

2023-11-20 22:00 UTC, crtrott commented on docs/source/API/core/view/view.rst
> +    template <class DataType [, class Space] [, class Layout] [, class MemoryTraits]>
Where is this coming from? It was correct before now its wrong?

2023-11-20 22:00 UTC, crtrott commented on docs/source/API/core/view/view.rst
> +The ``DataType`` template parameter is required, but the others are optional.  Ordering is enforced for only the first (``DataType``) and last (``MemoryTraits``) positions.  That means, for example,
This sentence is wrong. If you provide both Space and Layout, Layout has to come first.

2023-11-20 22:00 UTC, crtrott commented on docs/source/API/core/view/view.rst
> +  MemoryTraits specify how a data structure is accessed.
It is not a "data structure" which is accessed, but elements of the View, which more often than not are not structures in any C++ sense.

2023-11-20 22:00 UTC, crtrott commented on docs/source/API/core/view/view.rst
> +  - |Atomic|_: All accesses to the View will use atomic operations.
if we capitalize we should make it code font. Note that "view" is a general word referring to what `View` is a: a data structure with "view" semantics.

2023-11-20 22:00 UTC, crtrott commented on docs/source/API/core/view/view.rst
> +this change may yield warnings about comparing signed and unsigned integral types.0
random zero?

2023-11-20 22:00 UTC, crtrott commented on docs/source/API/core/view/view.rst
> +              ``View::required_allocation_size(layout)``.
Whats going on here? There is no layout parameter above? Did you try to merge the two constructors??

2023-11-20 22:00 UTC, crtrott commented on docs/source/API/core/view/view.rst
>  .. cppkokkos:function:: View( pointer_type ptr, const array_layout& layout)
This constructor has now no description?

2024-04-01 20:40 UTC, ajpowelsnl commented
No need for a wholesale revision of `View` documentation at this time; instead, make incremental changes (together with code updates) as needed.

2024-04-01 20:40 UTC, closed without merging