Added Kokkos compatibility documentation
kokkos/kokkos-core-wiki pull request #46
Opened 2022-06-14 23:56 UTC by nliber

Initial draft of what we mean by Kokkos compatibility

@ldh4

2022-06-15 21:13 UTC, JBludau commented
From slack:
Francesco: where is it written in the documentation/wiki that it is not legal to include a subdirectory?

Maybe we should mention that even though it is implicitly specified by saying "Kokkos_core.hpp" is the only public header. Might make the document more complete ...

2022-06-16 22:24 UTC, nliber commented
I will say something along the lines of not to directly include things in subdirectories.

Do we want to encourage/discourage/say nothing about looking in other headers to see the actual public interface?  In practical terms, the headers are in some sense always up to date, but they may accidentally have public things we really don't want users to rely upon.

2022-06-16 22:29 UTC, nliber commented
On a different library project, it was brought up that user defined macros could interfere with variable names, member functions, etc., including private ones.

I'll add something along the lines of user macros should also be prefaced with MYPROJECT_ (all cap unique name for the project followed by an underscore) to avoid collisions, either in the macro section or the very last section (which is essentially misc. rules).

2022-06-24 08:52 UTC, fnrizzi commented
@nliber I took the liberty of opening #61 which also serves as an example for next documentation session

2022-06-24 17:29 UTC, PhilMiller commented
There's a concern about how long compilation takes if we require all client code to include Kokkos_Core.hpp rather than exposing narrower headers as public. I recognize this isn't really the place to discuss that, though

2022-06-27 18:05 UTC, nliber commented on Compatibility.md
> +The experimentally support interface for Kokkos is in
Resolved in #73

2022-08-01 15:31 UTC, masterleinad requested changes
Use the new directories.

2022-08-09 00:34 UTC, nliber commented
Superceded by PR #136.

2022-08-09 00:34 UTC, closed without merging