Initialization.rst: fix superscripts and render code as code
kokkos/kokkos-core-wiki pull request #531
Opened 2024-06-07 19:26 UTC by RL-S

Two superscripts weren't rendered as such, because the leading (escaped) space before ':sup:`<num>`' was missing. Also, the table of command line arguments was rendered as text, rendering double dashes as em or en dashes (at least in my browser). Finally, removed two extraneous words in the "Initialization by struct" paragraph. Also, why is this .rst, but other parts are .md? I think that leads to a lot of code being simply rendered as italics: anything inside single backticks without "code::" before it.

2024-06-07 19:32 UTC, masterleinad approved these changes
Looks good to me! Thanks!

2024-06-10 23:48 UTC, ajpowelsnl commented
Hi @RL-S - For now, our focus is the API Guide (see [comment](https://github.com/kokkos/kokkos-core-wiki/pull/535#issuecomment-2159504287)), unless tasking has changed (?).  LMK if you have any questions about revising the API Guide.

2024-07-03 17:59 UTC, ajpowelsnl requested changes
Just a few details to fix up

2024-07-03 17:59 UTC, ajpowelsnl commented
ping @RL-S

2024-07-13 17:59 UTC, RL-S commented
> ping @RL-S

Was on holiday until yesterday. See [new commit](https://github.com/kokkos/kokkos-core-wiki/pull/531/commits/2ce6439b0e4ff3d72ee187c1174a96b5eb04e6c5), should resolve it.

2024-07-15 18:32 UTC, ajpowelsnl approved these changes
It's good once the question around a working link to Table-5.1 is finalized.

2024-07-15 18:32 UTC, ajpowelsnl commented on docs/source/ProgrammingGuide/Initialization.rst
> +
By link, I meant a URL one can click for additional information.  Is  "< Table clio-pts>" a clickable URL?

2024-07-15 18:32 UTC, ajpowelsnl commented on docs/source/ProgrammingGuide/Initialization.rst
> +Instead of giving `Kokkos::initialize() <../API/core/initialize_finalize/initialize.html>`_ command-line arguments, one may directly pass in initialization parameters using the `Kokkos::Initializatio
Is there API documentation on using the struct for initialization settings?   If not, that might be something to do, comparing one method to the other.  I have the same question as above about the link to Table 5.1.

2024-07-16 07:22 UTC, RL-S commented on docs/source/ProgrammingGuide/Initialization.rst
> +
It's supposed to be one, yes. You click it, and it jumps to Table 5.1. For that, I put an anchor above it, in line 60:
`.. Table_cli-opts:`
I'm not an expert in reStructured text, and neither is GitHub's preview, so references are a bit iffy. But the syntax
``Table 5.1 <Table_cli-opts>`_`
is supposed to _display_ 'Table 5.1' and the _reference target_ is what's within the angle braces (`< >`).

2025-01-28 18:31 UTC, merged