Mention Kokkos::Threads
kokkos/kokkos-core-wiki pull request #546
Opened 2024-06-21 08:40 UTC by PhilipDeegan

the page https://kokkos.org/kokkos-core-wiki/API/core/execution_spaces.html

doesn't mention `Kokkos::Threads`

yet `Threads` is referenced from https://kokkos.org/kokkos-core-wiki/API/core/Execution-Policies.html

2024-06-21 12:17 UTC, masterleinad approved these changes

2024-06-28 19:20 UTC, tpadioleau approved these changes

2024-07-02 09:47 UTC, cedricchevalier19 requested changes

2024-07-02 09:47 UTC, cedricchevalier19 commented on docs/source/API/core/execution_spaces.rst
> +------------------
```suggestion
``Kokkos::Threads``
-------------------
```

2024-07-02 13:56 UTC, cedricchevalier19 approved these changes

2024-07-02 13:58 UTC, merged